<?php

namespace EmotionBundle\Form;

use Doctrine\DBAL\Types\BooleanType;
use EmotionBundle\Entity\Users;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LocationType extends AbstractType
{
	public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
        	->add('id_vehicule', TextType::class,array('required' => false));
        	->add('id_users', TextType::class,array('required' => false));
            ->add('date_location', DateType::class, [
                'required' => false,
                'widget' => 'single_text',
            ]);
            ->add('prix_location', TextType::class,array('required' => false))
            ->add('retour_location', DateType::class, [
                'required' => false,
                'widget' => 'single_text',
            ]);

    }
}