<?php
/**
 * Created by PhpStorm.
 * User: Antoine.B
 * Date: 26/08/2017
 * Time: 01:55
 */


namespace EmotionBundle\Form;

use EmotionBundle\Entity\Location;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class LocationType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('date_location', DateType::class, [
                'required' => false,
                'widget' => 'single_text',
            ])
            ->add('retour_location', DateType::class, [
                'required' => false,
                'widget' => 'single_text',
            ])
            ->add('prix_location', IntegerType::class,array('required' => false))
          ;

    }

}

