<?php
/**
 * Created by PhpStorm.
 * User: Antoine.B
 * Date: 26/08/2017
 * Time: 18:26
 */


namespace EmotionBundle\Form;

use Doctrine\DBAL\Types\BooleanType;
use EmotionBundle\Entity\Users;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UsersType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('nom', TextType::class,array('required' => false))
            ->add('prenom', TextType::class,array('required' => false))
            ->add('birthday', DateType::class, [
                'required' => false,
                'widget' => 'single_text',
            ])
            ->add('adresse', TextType::class,array('required' => false))
            ->add('phone', TextType::class,array('required' => false))
            ->add('nb_permis', TextType::class,array('required' => false))
            ->add('email', TextType::class,array('required' => false))
            ->add('password', TextType::class,array('required' => false));

    }

}