user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

emotion:
    resource: "@EmotionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path: /
    defaults: { _controller: AppBundle:Default:index }
