setVehicule:
    path: /addvehicule
    defaults: { _controller: EmotionBundle:Default:InsertVehicule }

setLocation:
    path: /addlocation/{id}
    defaults: { _controller: EmotionBundle:Default:InsertLocation }

updateVehicule:
    path: /updvehicule/{id}
    defaults: { _controller: EmotionBundle:Default:UpdateVehicule }

Vehicules:
    path: /cars
    defaults: { _controller: EmotionBundle:Default:PageVehicule }

Scooters:
    path: /scooters
    defaults: { _controller: EmotionBundle:Default:PageScooters }

filtervehicule:
    path: /filters/{param}/{param2}/{param3}/{param4}
    defaults: { _controller: EmotionBundle:Default:Filters }

about_us:
    path: /about_us
    defaults: { _controller: EmotionBundle:Default:Presentation }

fidelites:
    path: /fidelites
    defaults: { _controller: EmotionBundle:Default:fidelites }

getLocations:
    path: /mes_locations
    defaults: { _controller: EmotionBundle:Default:MesLocations }