<?php
/**
 * Created by PhpStorm.
 * User: Antoine.B
 * Date: 26/08/2017
 * Time: 18:59
 */

namespace EmotionBundle\Entity;

/**
 * CandidatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends \Doctrine\ORM\EntityRepository
{
    public function FilterVehicule($param,$param2,$param3,$param4){
        $rawSQL = "SELECT * FROM `vehicule`WHERE";
        $rawSQL .= " ville_depart=".$param." OR date_debut_dispo=".$param2." OR date_fin_dispo=".$param3." OR nb_kilometres=".$param4;
        $stmt = $this->getEntityManager()->getConnection()->prepare($rawSQL);
        $stmt->execute([]);
        return $stmt->fetchAll();
    }
}
